Repository moss-foundation/moss, pull requests merged in 2024-11, with the labels that each got.

#120 fix: update readme and change logic for checking home directory & user config file
  Cargo.lock
  Cargo.toml
  README.md
  internal/platform/configuration/src/user_settings.rs
  view/desktop/bin/Cargo.toml
  view/desktop/bin/src/commands/cmd_dummy.rs
  view/desktop/bin/src/lib.rs
  view/desktop/bin/src/utl.rs
Labels: bug, documentation

#129 feat(MOSSMVP-229): Fix the workspace dependencies
  Cargo.lock
  Makefile
Labels: makefile

#128 feat(MOSSMVP-229): Implement CLI entry point with `info` command
  Cargo.lock
  view/desktop/bin/Cargo.toml
  view/desktop/bin/src/cli.rs
  view/desktop/bin/src/cli/cli_info.rs
  view/desktop/bin/src/lib.rs
  view/desktop/bin/tauri.conf.json
Labels: feature, rust

#127 fix(MOSSMVP-234): Fix deadlock on clicking New Window button
  view/desktop/bin/src/cli.rs
  view/desktop/bin/src/cli/cli_info.rs
  view/desktop/bin/src/commands/cmd_window.rs
  view/desktop/bin/src/lib.rs
  view/desktop/bin/src/menu.rs
  view/desktop/bin/src/window.rs
Labels: bug, os: mac, os: windows

#133 feat(MOSSMVP-238): Frontend Finalizing UI Headbar
  .vscode/settings.json
  pnpm-lock.yaml
  view/desktop/src/components/Accordion.tsx
  view/desktop/src/components/ActionsGroup.tsx
  view/desktop/src/components/HeadBar/ActionsBar.tsx
  view/desktop/src/components/HeadBar/DNDWrapper.tsx
  view/desktop/src/components/HeadBar/HeadBar.tsx
  view/desktop/src/components/HeadBar/HeadBarButton.tsx
  view/desktop/src/components/HeadBar/WidgetBar.tsx
  view/desktop/src/components/LaunchPad.tsx
  view/desktop/src/components/index.ts
  view/desktop/src/components/pages/Home.tsx
  view/shared/ui/package.json
  view/shared/ui/src/DropdownMenu.stories.tsx
  view/shared/ui/src/DropdownMenu.tsx
  view/shared/ui/src/DropdownMenu.types.ts
  view/shared/ui/src/Menu/Content.tsx
  view/shared/ui/src/Menu/DropdownMenu/DropdownMenu.stories.tsx
  view/shared/ui/src/Menu/DropdownMenu/DropdownMenu.tsx
  view/shared/ui/src/Menu/Item.tsx
  view/shared/ui/src/index.ts
Labels: typescript, improvement

#132 DevOps(MOSSMVP-263): Set up pre-commit `rustfmt` hook
  .husky/pre-commit
  package.json
Labels: dependencies

#139 refactor(MOSSMVP-267): remove all specta dependencies
  Cargo.lock
  Cargo.toml
  internal/workbench/desktop/Cargo.toml
  lib/moss_theme/package.json
  pnpm-workspace.yaml
  sdk-ts/moss-models/package.json
  sdk-ts/moss-models/src/index.ts
  sdk-ts/moss-models/tsconfig.json
  tools/themegen/package.json
  tsconfig.json
  view/desktop/bin/Cargo.toml
  view/desktop/bin/src/commands/cmd_dummy.rs
  view/desktop/bin/src/commands/cmd_window.rs
  view/desktop/bin/src/lib.rs
  view/desktop/bin/src/utl.rs
  view/desktop/src/bindings.ts
  view/desktop/src/components/pages/Home.tsx
  view/desktop/src/components/pages/Settings.tsx
  view/desktop/src/lib/backend/tauri.ts
  view/desktop/src/store/themes/themesHelpers.ts
  view/desktop/src/store/themes/themesThunks.ts
  view/desktop/src/utils/index.ts
  view/shared/ui/package.json
  view/storybook/package.json
Labels: dependencies, improvement

#136 MOSSMVP-260-Improve-CONTRIBUTING.md
  .gitignore
  CONTRIBUTING.md
  README
  README.md
  internal/workbench/desktop/models/src/appearance.rs
Labels: documentation

#144 feat:(MOSSMVP-274): theme api modification
  .vscode/settings.json
  Cargo.lock
  internal/workbench/desktop/models/bindings/appearance.ts
  internal/workbench/desktop/models/schema/ThemeSchema.json
  internal/workbench/desktop/models/schema/TypeSpec.tsp
  internal/workbench/desktop/models/src/appearance.rs
  pnpm-lock.yaml
  tools/icongen/index.ts
  tools/icongen/package.json
  tools/icongen/tsconfig.json
  view/desktop/bin/Cargo.toml
  view/desktop/bin/src/commands.rs
  view/desktop/bin/src/commands/cmd_dummy.rs
  view/desktop/bin/src/commands/cmd_fs.rs
  view/desktop/bin/src/commands/cmd_window.rs
  view/desktop/bin/src/lib.rs
  view/desktop/package.json
  view/desktop/src/App.tsx
  view/desktop/src/api/appearance/index.ts
  view/desktop/src/assets/moss-dark.css
  view/desktop/src/assets/moss-light.css
  view/desktop/src/assets/moss-pink.css
  view/desktop/src/atoms/themeAtom.ts
  view/desktop/src/components/AppLayout.tsx
  view/desktop/src/components/HeadBar/Controls/LinuxControls.tsx
  view/desktop/src/components/HeadBar/Controls/WindowsControls.tsx
  view/desktop/src/components/Sidebar.tsx
  view/desktop/src/components/ThemeSelector.tsx
  view/desktop/src/components/ThemeSwitcher.tsx
  view/desktop/src/components/TitleBar.tsx
  view/desktop/src/components/app/Provider.tsx
  view/desktop/src/components/app/RootLayout.tsx
  view/desktop/src/components/app/ThemeProvider.tsx
  view/desktop/src/components/index.ts
  view/desktop/src/components/pages/Home.tsx
  view/desktop/src/components/pages/Logs.tsx
  view/desktop/src/components/pages/Settings.tsx
  view/desktop/src/hooks/useChangeTheme.ts
  view/desktop/src/hooks/useFetchThemes.ts
  view/desktop/src/hooks/useInitializeApp.ts
  view/desktop/src/lib/backend/tauri.ts
  view/desktop/src/store/index.ts
  view/desktop/src/store/themes/index.ts
  view/desktop/src/store/themes/themesHelpers.ts
  view/desktop/src/store/themes/themesSlice.ts
  view/desktop/src/store/themes/themesThunks.ts
  view/shared/config-tailwind/tailwind.config.ts
  view/shared/config-typescript/react-library.json
  view/shared/ui/src/Icon.stories.tsx
  view/shared/ui/src/Icon.tsx
  view/shared/ui/src/index.ts
  view/shared/ui/src/tailwind/index.tsx
  view/shared/ui/tsconfig.json
Labels: typescript, improvement

#148 feat(MOSSMVP-273): Service for generating CSS based on a JSON theme file
  Cargo.lock
  Cargo.toml
  crates/moss-fs/Cargo.toml
  crates/moss-html/Cargo.toml
  crates/moss-str/Cargo.toml
  crates/moss-themeconv/Cargo.toml
  crates/moss-themeconv/src/json_converter.rs
  crates/moss-themeconv/src/lib.rs
  crates/moss-themeconv/src/model.rs
  crates/moss-themeconv/src/util.rs
  crates/moss-themeconv/tests/light-theme.test.json
  crates/moss-uikit/Cargo.toml
  internal/workbench/desktop/models/bindings/appearance.ts
  internal/workbench/desktop/models/src/appearance.rs
Labels: feature, rust

#149 feat(MOSSMVP-282): Frontend Integration of the new version of ESLint
  .eslintignore
  .vscode/settings.json
  pnpm-lock.yaml
  view/desktop/.eslintrc.js
  view/desktop/eslint.config.js
  view/desktop/package.json
  view/desktop/src/App.tsx
  view/desktop/src/components/HeadBar/Controls/Controls.tsx
  view/desktop/src/components/HeadBar/HeadBar.tsx
  view/desktop/src/components/HeadBar/WidgetBar.tsx
  view/desktop/src/components/LaunchPad.tsx
  view/desktop/src/components/Menu.tsx
  view/desktop/src/components/Resizable.stories.tsx
  view/desktop/src/components/Resizable.tsx
  view/desktop/src/components/SidebarGeneral.tsx
  view/desktop/src/components/StatusBar.stories.ts
  view/desktop/src/components/pages/Home.tsx
  view/desktop/src/events/eventBus.ts
  view/desktop/src/hooks/useInitializeApp.ts
  view/desktop/src/lib/instantiation/instantiationService.ts
  view/desktop/src/main.tsx
  view/desktop/tsconfig.app.json
  view/desktop/tsconfig.json
  view/shared/config-eslint/README.md
  view/shared/config-eslint/eslint.config.js
  view/shared/config-eslint/library.js
  view/shared/config-eslint/next.js
  view/shared/config-eslint/package.json
  view/shared/config-eslint/react.js
  view/shared/config-eslint/web.js
  view/shared/config-typescript/react-library.json
  view/shared/docs/index.md
  view/shared/docs/shared_doc.md
  view/shared/ui/.eslintrc.js
  view/shared/ui/eslint.config.js
  view/shared/ui/package.json
  view/shared/ui/src/Icon.stories.tsx
  view/shared/ui/src/Link.tsx
  view/shared/ui/src/Menu/ContextMenu/ContextMenu.stories.tsx
  view/shared/ui/src/Menu/ContextMenu/ContextMenu.tsx
  view/shared/ui/src/Menu/DropdownMenu/DropdownMenu.stories.tsx
  view/shared/ui/src/Menu/DropdownMenu/DropdownMenu.tsx
  view/shared/ui/src/Menu/SubMenu.tsx
  view/shared/ui/src/MenuItem.tsx
  view/shared/ui/src/Tooltip.stories.tsx
  view/shared/ui/src/tailwind/index.tsx
  view/storybook/.eslintrc.cjs
  view/storybook/.storybook/preview.tsx
  view/storybook/eslint.config.js
  view/storybook/package.json
  view/storybook/tsconfig.app.json
  view/web/.eslintrc.js
  view/web/eslint.config.js
Labels: typescript, improvement
